version: '3'
services:
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/usr/src/api
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ../../public:/data/public
      - ../../../shared:/shared
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      DEPLOY_RUNNER: ${CURRENT_UID:-1}
      APACHE_RUN_USER: "#${CURRENT_UID:-1}"
networks:
  default:
    external:
      name: staging_network