version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test-unit:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.6.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: exit
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
  deploy:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.6.0
    steps:
      - add_ssh_keys:
          fingerprints:
              - "d3:8e:38:fd:c9:0a:7d:99:39:92:70:92:bb:2d:27:a9"
      - deploy:
          name: deployment
          command: ssh -o "StrictHostKeyChecking no" root@134.209.103.187 "cd /var/www && rm -rf expressjs && rm -rf api && git clone https://github.com/yanaphats/expressjs.git api && cd api/deploy && sh deployment.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
                - uat
                - master
      - test-unit:
          requires:
            - build
          filters:
            branches:
              only:
                - development
                - uat
                - master
      - deploy:
          requires:
            - test-unit
          filters:
            branches:
              only:
                - uat
                - master
